package appconfigurationapi

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "github.com/Azure/azure-sdk-for-go/services/appconfiguration/1.0/appconfiguration"
    "github.com/Azure/go-autorest/autorest"
)

        // BaseClientAPI contains the set of methods on the BaseClient type.
        type BaseClientAPI interface {
            CheckKeys(ctx context.Context, name string, after string, acceptDatetime string) (result autorest.Response, err error)
            CheckKeyValue(ctx context.Context, key string, label string, acceptDatetime string, ifMatch string, ifNoneMatch string, selectParameter []string) (result autorest.Response, err error)
            CheckKeyValues(ctx context.Context, key string, label string, after string, acceptDatetime string, selectParameter []string) (result autorest.Response, err error)
            CheckLabels(ctx context.Context, name string, after string, acceptDatetime string, selectParameter []string) (result autorest.Response, err error)
            CheckRevisions(ctx context.Context, key string, label string, after string, acceptDatetime string, selectParameter []string) (result autorest.Response, err error)
            DeleteKeyValue(ctx context.Context, key string, label string, ifMatch string) (result appconfiguration.KeyValue, err error)
            DeleteLock(ctx context.Context, key string, label string, ifMatch string, ifNoneMatch string) (result appconfiguration.KeyValue, err error)
            GetKeys(ctx context.Context, name string, after string, acceptDatetime string) (result appconfiguration.KeyListResultPage, err error)
                GetKeysComplete(ctx context.Context, name string, after string, acceptDatetime string) (result appconfiguration.KeyListResultIterator, err error)
            GetKeyValue(ctx context.Context, key string, label string, acceptDatetime string, ifMatch string, ifNoneMatch string, selectParameter []string) (result appconfiguration.KeyValue, err error)
            GetKeyValues(ctx context.Context, key string, label string, after string, acceptDatetime string, selectParameter []string) (result appconfiguration.KeyValueListResultPage, err error)
                GetKeyValuesComplete(ctx context.Context, key string, label string, after string, acceptDatetime string, selectParameter []string) (result appconfiguration.KeyValueListResultIterator, err error)
            GetLabels(ctx context.Context, name string, after string, acceptDatetime string, selectParameter []string) (result appconfiguration.LabelListResultPage, err error)
                GetLabelsComplete(ctx context.Context, name string, after string, acceptDatetime string, selectParameter []string) (result appconfiguration.LabelListResultIterator, err error)
            GetRevisions(ctx context.Context, key string, label string, after string, acceptDatetime string, selectParameter []string) (result appconfiguration.KeyValueListResultPage, err error)
                GetRevisionsComplete(ctx context.Context, key string, label string, after string, acceptDatetime string, selectParameter []string) (result appconfiguration.KeyValueListResultIterator, err error)
            PutKeyValue(ctx context.Context, key string, label string, entity *appconfiguration.KeyValue, ifMatch string, ifNoneMatch string) (result appconfiguration.KeyValue, err error)
            PutLock(ctx context.Context, key string, label string, ifMatch string, ifNoneMatch string) (result appconfiguration.KeyValue, err error)
        }

        var _ BaseClientAPI = (*appconfiguration.BaseClient)(nil)
